### ISSUE TITLE
Align center the heading

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO#47]
Align center the heading

**Comment by rohitsinghind** [comment]
hey, can u assign this to me

**Comment by rohitsinghind** [comment]
yeah sure

**Comment by singhkaran202** [comment]
Hello @YoshithaRathnayake, I'd love to work on this, if that's OK.
Could you please assign me this issue?

**Comment by komalsoni4** [comment]
please assign me this issue

**Comment by atharvabhoite7** [comment]
Hey @YoshithaRathnayake ! I'm interested in this. Please can you assign it to me?

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged!
