### ISSUE TITLE
Add the YAML logo to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO#65]
Add the YAML logo to the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198270706-dd72780f-dfa3-46cd-b149-e3f4c664fce1.png)

**Comment by Bwc9876** [comment]
Could I get this issue assigned to me?

**Comment by YoshithaRathnayake** [comment]
> Could I get this issue assigned to me?

Sure, go ahead @Bwc9876
