### ISSUE TITLE
Remove the SECURITY.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO#66]
Remove the SECURITY.md file

**Comment by kheersagar** [comment]
please assign this task to me

**Comment by YoshithaRathnayake** [comment]
> please assign this task to me

Sure, go ahead @kheersagar

**Comment by kheersagar** [comment]
please change the label to hacktoberfest-accepted

**Comment by YoshithaRathnayake** [comment]
> please change the label to hacktoberfest-accepted

Why don't you read the instructions of maintainer. We should add the hacktoberfest label to the issue and add the accepted label to the PR only, It's accepting don't worry @kheersagar
