### ISSUE TITLE
Increase the size of the yaml logo in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO#76]
Increase the size of the yaml logo in the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198431691-760c537b-224d-453a-9b7c-fe5849a89195.png)

**Comment by AniqJaved** [comment]
Can I work on this issue?

**Comment by YoshithaRathnayake** [comment]
> Can I work on this issue?

Sure, go ahead @AniqJaved

**Comment by Roxie2003** [comment]
Hey @YoshithaRathnayake can I work on this?
