### ISSUE TITLE
Use an `and` between the Boostrap and Yaml in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO#80]
Use an `and` between the Boostrap and Yaml in the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198676748-05582f7e-bc73-4af0-a409-15f8930b4def.png)

**Comment by Roxie2003** [comment]
please assign it to me

**Comment by siddhesh-desai** [comment]
Please assign it to me @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged! @Roxie2003  @siddhesh-desai
