### ISSUE TITLE
Capitalize all the programming languages in readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YOSHITHA-RATHNAYAKE-PRO#81]
Capitalize all the programming languages in readme.md file

![image](https://user-images.githubusercontent.com/97069900/198676869-9b88cd32-e6cc-4fdc-83cd-635c140ca302.png)

`JavaScript = JAVASCRIPT`
`Bootstrap = BOOTSTRAP`

**Comment by Roxie2003** [comment]
please assign it to me

**Comment by YoshithaRathnayake** [comment]
> please assign it to me

Sure, go ahead @Roxie2003
